configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/minknown.smk"
include: "rules/fastqs.smk"
include: "rules/qc.smk"


rule all:
    input:
        expand(
            "results/minknow/{experiment_id}_{sample_id}_throughput.csv",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        expand(
            "results/minknow/{experiment_id}_{sample_id}_pore.csv",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        expand(
            "results/minknow/{experiment_id}_{sample_id}_poreseq.csv",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        expand(
            "results/fastqs/{experiment_id}_{sample_id}.fastq.gz",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        expand(
            "results/qc/fastqc/{experiment_id}_{sample_id}_fastqc.zip",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        expand(
            "results/qc/fastqc/{experiment_id}_{sample_id}.html",
            zip,
            experiment_id=samples["experiment_id"],
            sample_id=samples["sample_id"],
        ),
        "results/qc/multiqc.html",
