configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/basecall.smk"
include: "rules/filter_basecalled.smk"
include: "rules/minimap2.smk"
include: "rules/statistics.smk"


rule all:
    input:
        "results/report.html",
