# DEFAULT
# path to experiment sheet (CSV format)
samples: config/experiments.csv


# BASECALLING
# define parameters for a specific rule
basecall: True
# dorado model 'fast', 'hac' or 'sup'
dorado_model: sup
# minimum mean quality for read
minimum_quality: 10

# MAPPING
# allowed errors in primers
allowed_primer_errors: 5
