samples: config/experiments.csv
# BASECALLING
# define parameters for a specific rule
basecall: True
# dorado model 'fast', 'hac' or 'sup'
dorado_model: sup


#basecalling parameters
basecalling:
  basecall:
    label: Enable basecall #label near widget
    type: checkbox
    value: false
  dorado_model:
    label: Dorado model
    options:
    - fast
    - hac
    - sup
    type: combobox
    value: fast
  input_line:
    label: Dorado model
    type: line
    value: fast
  input_path:
    label: Dorado model
    type: path
    file_type: folder #type of file that will be accessible via FileDialog
    value: Select path


#experiments table
experiments:
- column: Path to Sample
  type: folder #type of file that will be accessible via FileDialog
- column: Path to Reference
  type: fa
- column: forward_primer
  type: plaintxt
- column: reverse_primer
  type: plaintxt
