# config.yaml

# path or URL to experiment sheet (CSV format)
samples: config/experiments.csv

# define directories
output_folder: results # default value

# define parameters for a specific rule
basecall: True
# dorado model 'fast', 'hac' or 'sup'
dorado_model: sup

# path to reference files
reference: resources/ref.fa

# parameters for computational resources
threads: 4
memory: 36G
