# config.yaml

# path or URL to experiment sheet (CSV format)
experiments: config/experiments.csv

# define directories
out_dir: results # default value

# define parameters for a specific rule
basecall: True

# path to reference files
reference: resources/ref.fa

# parameters for computational resources
threads: 4
memory: 36G
