basecall: true
basecalling:
  basecall:
    label: Enable basecall
    type: checkbox
    value: false
  dorado_model:
    label: Dorado model
    options:
    - fast
    - hac
    - sup
    type: combobox
    value: fast
  input_line:
    label: Dorado model
    type: line
    value: fast
  input_path:
    file_type: folder
    label: Dorado model
    type: path
    value: Select path
dorado_model: sup
experiments:
- column: Path to Sample
  type: folder
- column: Path to Reference
  type: fa
- column: forward_primer
  type: plaintxt
- column: reverse_primer
  type: plaintxt
samples: config/experiments.csv
