basecalling:
  allowed_primer_errors:
    label: Allowed primers errors
    type: line
    value: '5'
  dorado_model:
    label: Dorado model
    options:
    - fast
    - hac
    - sup
    type: combobox
    value: fast
  minimum_quality:
    label: Minimum Quality
    type: line
    value: '10'
experiments:
- column: path_to_sample
  type: folder
- column: path_to_reference
  type: fa
- column: forward_primer
  type: plaintxt
- column: reverse_primer
  type: plaintxt
