name: Tests

on:
  push


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
            submodules: recursive
            fetch-depth: 0
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_PYTHON_PYLINT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: actions/checkout@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --lint"

  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test workflow
      uses: actions/checkout@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --use-conda --show-failed-logs --cores 3 --conda-cleanup-pkgs cache --all-temp"

    - name: Test report
      uses: actions/checkout@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --report report.zip"
